version: "3"
services:
    api:
        image: "employee"  
        build: 
            context: .
            dockerfile: Dockerfile
        ports:
            - "5000:80"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "SqlServer2019"
            ACCEPT_EULA: "Y"
            MSSQL_TCP_PORT: "1433"
        ports: 
            - "1400:1433"